/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mgh.edd;

public class App {
    public String getGreeting() {
        return "las 3 ventajas de GitHub son las siguientes:1. puedes acceder a tus archivos siempre que quieras desde cualquie dispositivo 2. es gratis 3. es mas facil el manejo de las modificaciones de los arhcivos";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
